### ISSUE TITLE
Loading unicom-ig with ember returns an error on branch master

### ISSUE THREAD

**Issue by G-DPP** [hl7-eu/unicom-ig#83]
As we agreed, we are setting up the jpa-starter: [https://jpa.unicom.datawizard.it/](https://jpa.unicom.datawizard.it/) . We are trying to load the unicom-ig with ember. We managed to load the ig from the deployable branch but we got problem with master branch. 
The error that returns is:
```
ember  | java.lang.IllegalStateException: Failed to execute ApplicationRunner
ember  | 	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:765) ~[spring-boot-2.7.4.jar!/:2.7.4]
ember  | 	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:752) ~[spring-boot-2.7.4.jar!/:2.7.4]
ember  | 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315) ~[spring-boot-2.7.4.jar!/:2.7.4]
ember  | 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1306) ~[spring-boot-2.7.4.jar!/:2.7.4]
ember  | 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1295) ~[spring-boot-2.7.4.jar!/:2.7.4]
ember  | 	at dk.jkiddo.EmberApplication.main(EmberApplication.java:81) ~[classes!/:0.6.0-SNAPSHOT]
ember  | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
ember  | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[na:na]
ember  | 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
ember  | 	at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[na:na]
ember  | 	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) ~[main.jar:0.6.0-SNAPSHOT]
ember  | 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:108) ~[main.jar:0.6.0-SNAPSHOT]
ember  | 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) ~[main.jar:0.6.0-SNAPSHOT]
ember  | 	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:65) ~[main.jar:0.6.0-SNAPSHOT]
ember  | Caused by: ca.uhn.fhir.rest.server.exceptions.UnprocessableEntityException: HTTP 422 : HAPI-0522: Unable to store a Bundle resource on this server with a Bundle.type value of: transaction. Note that if you are trying to perform a FHIR transaction or batch operation you should POST the Bundle resource to the Base URL of the server, not to the /Bundle endpoint.
ember  | 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:na]
ember  | 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[na:na]
ember  | 	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:na]
ember  | 	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[na:na]
ember  | 	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[na:na]
ember  | 	at ca.uhn.fhir.rest.server.exceptions.BaseServerResponseException.newInstance(BaseServerResponseException.java:310) ~[hapi-fhir-base-6.2.1.jar!/:na]
ember  | 	at ca.uhn.fhir.rest.client.impl.BaseClient.invokeClient(BaseClient.java:376) ~[hapi-fhir-client-6.2.1.jar!/:na]
ember  | 	at ca.uhn.fhir.rest.client.impl.GenericClient$BaseClientExecutable.invoke(GenericClient.java:541) ~[hapi-fhir-client-6.2.1.jar!/:na]
ember  | 	at ca.uhn.fhir.rest.client.impl.GenericClient$TransactionExecutable.execute(GenericClient.java:2170) ~[hapi-fhir-client-6.2.1.jar!/:na]
ember  | 	at dk.jkiddo.EmberApplication.emitBundle(EmberApplication.java:141) ~[classes!/:0.6.0-SNAPSHOT]
ember  | 	at dk.jkiddo.EmberApplication.run(EmberApplication.java:120) ~[classes!/:0.6.0-SNAPSHOT]
ember  | 	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:762) ~[spring-boot-2.7.4.jar!/:2.7.4]
ember  | 	... 13 common frames omitted
```

In this line it says that there is an error on bundle resource endpoint
```
ember  | Caused by: ca.uhn.fhir.rest.server.exceptions.UnprocessableEntityException: HTTP 422 : HAPI-0522: Unable to store a Bundle resource on this server with a Bundle.type value of: transaction. Note that if you are trying to perform a FHIR transaction or batch operation you should POST the Bundle resource to the Base URL of the server, not to the /Bundle endpoint.
```
so we assume that the error comes from ember and not from the ig.

Has anyone faced this problem before? Does a solution already exist or we need to fork ember and fix this error?

**Comment by costateixeira** [comment]
Closed as not applicable
